config/routes.rb
AmazonApp::Application.routes.draw do

  resources :sessions, :only => [:new, :create]

  match "signup" => "users#new", :as => "signup"
  match "logout" => "sessions#destroy", :as => "logout"
  match "login" => "sessions#new", :as => "login"

  resources :users, :only => [:new, :create, :show]

  post 'user/add_to_shopping_cart' => 'users#add_to_shopping_cart', :as => 'user_shopping_cart'

  resources :items

  post 'reviews/new/:item_id' =>  'reviews#create', :as => 'new_review'
  resources :reviews





  root :to => "items#index"
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :price, :user_id

  has_many :reviews
  belongs_to :user

  def available?
    self.user.blank?
  end

  def self.available_items?
    available_items = Item.where(:user_id => nil)

    available_items.length > 0
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :content, :user_id, :item_id

  belongs_to :user
  belongs_to :item

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :password, :username, :password_confirmation

  has_many :reviews
  has_many :items

  validates :username, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  helper_method :current_user

  def require_authentication
    if current_user.nil?
      redirect_to  root_path, :alert => "You must be logged in."
    end
  end

  def require_admin_authentication
    if !current_user.nil? && !current_user.is_admin?
      redirect_to root_path, :alert => "You must be logged in as an admin."
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @uniques = @items.uniq{ |item| item.name }
    @unique_count = @items.group_by{|item| item.name }.map{ |k, v| [k, v.count] }
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.where(:name => @item.name)
    @review = Review.new
    @user = current_user
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(params[:item])

    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(params[:item])
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to items_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(params[:review])
    @item_id = params[:item_id]
    @review.item_id = @item_id

    if @review.save
      redirect_to item_path(@item_id)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    if @review.update_attributes(params[:review])
      redirect_to reviews_path
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to reviews_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by_username(params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:notice] = "Your email or password was not correct"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_authentication, :only => [:new, :create]
  skip_before_filter :require_admin_authentication, :only => [:new, :create, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  def add_to_shopping_cart
    @user = current_user
    @item = Item.find(params[:item_id])

    @item.user_id = @user.id
    @item.save

    redirect_to user_path(@user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items#index</h1>

<div>

  <div id="items_container">
    <% @uniques.each do |item| %>
    <div id="items_container_item_name">
      Name:  <%= link_to item.name, item %>
    </div>
    <div id="items_container_item_price">
      Price: <%= item.price %>
    </div>
    <% end %>
  </div> <!-- items_container -->

    <% @unique_count.map do |count| %>
    <div id="count_container">
      <%= count.first %> Count: <%= count.last %>
    </div>
    <% end %>

</div>
<p> Item Counts:  <%= @unique_count %></p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>Items#show</h1>

<h2><%= @item.name %></h2>
<h4>Price:  <%= @item.price %></h4>

<% @items.each do |item| %>
  <% item.reviews.each do |review| %>
    <p><%= review.content %></p>
  <% end %>
<% end %>

<p>Add to Shopping Cart:
  <%= form_tag  user_shopping_cart_path, :method => 'post' do %>
  <%= hidden_field_tag :user_id, @user.id %>
  <%= hidden_field_tag :item_id, @item.id %>

  <%= button_tag "Submit" %>
  <% end %>
</p>


<%= form_for @review, :url => new_review_path(@item.id), :method => 'post' do |f| %>
<%= f.label "Write a Review of This Product" %><br>
<%= f.text_area :content %><br>
<%= f.submit %>
<% end %>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmazonApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <div id="navbar">
      <ul>
        <li id="home" class="navbar_buttons">
          <a href="/">Home</a>
        </li>
        <% if current_user %>
        <li class="navbar_buttons">
          <%= link_to "Log Out", logout_path %>
        </li>
        <li id="logged_in" class="navbar_buttons">
          Logged in as <%= current_user.username %>
        </li>
        <% else %>
        <li class="navbar_buttons">
          <%= link_to "Sign-Up", login_path %>
        </li>
        <li class="navbar_buttons">
          <%= link_to "Log-In", login_path %>
        </li>
        <% end %>
<!--         <li id="admin" class="navbar_buttons">
          Admin
        </li> -->
      </ul>
    </div>
  </nav>

<%= yield %>

</body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Shopping Cart</p>

<% @user.items.each do |item| %>
  <p><%= item.name %></p>
  <% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>